-- Seed: jogadores reais das listas WhatsApp (Quarta/Segunda/Sábado)
insert into players (name, slug, stars, roles) values
  ('Cineraria',   'cineraria',   3, '{passador,atacante}'),
  ('Dudu',        'dudu',        3, '{atacante}'),
  ('Brenna',      'brenna',      3, '{passador}'),
  ('Marília',     'marilia',     3, '{passador}'),
  ('Kovacs',      'kovacs',      4, '{levantador,atacante}'),
  ('Fabio',       'fabio',       3, '{atacante}'),
  ('Rafa',        'rafa',        3, '{atacante}'),
  ('Caio',        'caio',        3, '{passador}'),
  ('Kaiser',      'kaiser',      3, '{atacante}'),
  ('Caldas',      'caldas',      3, '{passador,atacante}'),
  ('Gabriel',     'gabriel',     3, '{atacante}'),
  ('Alicia',      'alicia',      3, '{passador}'),
  ('Diane',       'diane',       3, '{passador}'),
  ('Raina',       'raina',       3, '{passador}'),
  ('Dhonatas',    'dhonatas',    3, '{atacante}'),
  ('Carlim',      'carlim',      3, '{atacante}'),
  ('Samuel',      'samuel',      3, '{atacante}'),
  ('Cadu',        'cadu',        3, '{passador,atacante}'),
  ('Getúlio',     'getulio',     3, '{atacante}'),
  ('Larissy',     'larissy',     3, '{passador}'),
  ('Filipe',      'filipe',      3, '{atacante}'),
  ('Bianca',      'bianca',      3, '{passador}'),
  ('Ermeson',     'ermeson',     3, '{levantador,passador}'),
  ('Emerson',     'emerson',     3, '{atacante}'),
  ('Matheus',     'matheus',     3, '{atacante}'),
  ('Maria',       'maria',       3, '{passador}'),
  ('Super Meliante','super-meliante', 3, '{atacante}'),
  ('Vitinho',     'vitinho',     3, '{atacante}'),
  ('André',       'andre',       3, '{atacante}'),
  ('Neto',        'neto',        3, '{atacante}'),
  ('Marcos',      'marcos',      3, '{atacante}'),
  ('Alisson',     'alisson',     3, '{passador}')
on conflict (slug) do nothing;
